version: '3'

services:
  server:
    build: ./
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/my_auction_rest"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres11"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
    depends_on:
      - db
    
  db:
    image: 'postgres:13.1-alpine'
    container_name: db
    environment:
      POSTGRES_DB: "my_auction_rest"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres11"
    volumes:
      - ./db:/docker-entrypoint-initdb.d
      - my_auction_rest_pg_data:/var/lib/postgresql/data
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5.7
    environment:
      PGADMIN_DEFAULT_EMAIL: "developer@enail.com"
      PGADMIN_DEFAULT_PASSWORD: "pgadmin1"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    ports:
      - "5050:80"
    restart: unless-stopped

volumes:
  my_auction_rest_pg_data:
